### GET orders
GET http://localhost:3000/order

### GET order by id
GET http://localhost:3000/order/1

### POST order
POST http://localhost:3000/order

### PUT order
PUT http://localhost:3000/order/1

### DELETE order
DELETE http://localhost:3000/order/1